### ISSUE TITLE
12HR Time

### ISSUE THREAD

**Issue by argentdeux** [ConorTheDev/Chrono#1]
When the time is set to 12hour time, the world clock time with Chrono shows as 7:35AM:08
![FB78E8C4-59AA-4E2F-9017-8A14DB69EFF4](https://user-images.githubusercontent.com/32601263/59506797-20a3df00-8ea1-11e9-9ac6-4330b7b67b3b.png)

**Comment by ConorTheDev** [comment]
Thanks for the report! Will fix and release in 1.1.1

**Comment by ConorTheDev** [comment]
@argentdeux, v.1.1.1 has been submitted to Packix to fix your bug.

Commit:
https://github.com/ConorTheDev/Chrono/commit/b0093225c8342e90372d42b0953a6a7d9bb5357c

Thanks for the report and I hope you enjoy Chrono!

**Comment by argentdeux** [comment]
Super fast response and fix, thank you!
